name: Cleanup Terraform Services

# Run this workflow only after verifying new resources function as expected.
on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      REGION: europe-west1
      ENVIRONMENT: prod
      TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: gcloud

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -migrate-state

      - name: Disable deprecated services
        run: |
          terraform apply -lock-timeout=5m -auto-approve \
            -target=google_project_service.firebasehosting
