name: debug-tag

on:
  push:
    tags:
      - '**'

jobs:
  log-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show GitHub context
        run: |
          echo "ref=$GITHUB_REF"
          echo "ref_name=$GITHUB_REF_NAME"
          echo "event_name=$GITHUB_EVENT_NAME"
          echo "sha=$GITHUB_SHA"
          echo "actor=$GITHUB_ACTOR"
