name: Deploy Terraform

on:
  push:
    paths:
      - 'infra/**'
    branches:
      - main

  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      REGION: europe-west1
      ENVIRONMENT: prod
      TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: gcloud

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Migrate Firebase service state
        run: |
          if terraform state list | grep -Fq 'google_project_service.apis["firebase.googleapis.com"]'; then
            terraform state mv 'google_project_service.apis["firebase.googleapis.com"]' google_project_service.firebase_api
          fi
          if terraform state list | grep -Fq 'google_project_service.apis["firebaserules.googleapis.com"]'; then
            terraform state mv 'google_project_service.apis["firebaserules.googleapis.com"]' google_project_service.firebaserules
          fi

      - name: Enable core GCP APIs
        run: |
          terraform apply -auto-approve \
            -target=google_project_service.firestore \
            -target=google_project_service.identitytoolkit \
            -target=google_project_service.cloudfunctions \
            -target=google_project_service.compute \
            -target=google_project_service.run \
            -target=google_project_service.artifactregistry \
            -target=google_project_service.cloudscheduler \
            -target=google_project_service.firebaserules

      - name: Terraform Plan
        run: terraform plan -lock-timeout=5m -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -lock-timeout=5m -auto-approve tfplan
