name: gcp-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: gcp-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    defaults:
      run:
        working-directory: infra
    env:
      REGION: europe-west1
      GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate environment id
        id: environment
        run: |
          UUID="$(uuidgen | tr 'A-Z' 'a-z')"
          SHORT_ID="$(printf '%s' "$UUID" | md5sum | cut -c1-8)"
          ENVIRONMENT="t-${SHORT_ID}"
          echo "ENVIRONMENT=$ENVIRONMENT" >> "$GITHUB_ENV"
          echo "TF_VAR_environment=$ENVIRONMENT" >> "$GITHUB_ENV"
          echo "TF_VAR_database_id=$ENVIRONMENT" >> "$GITHUB_ENV"
          echo "environment=$ENVIRONMENT" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build cloud function sources
        working-directory: ./
        run: |
          npm ci
          npm run build:cloud

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}
          install_components: alpha

      - name: Log Google Cloud authentication details
        run: |
          gcloud auth list
          gcloud config list account
          gcloud config get-value project

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Cache Terraform plugin dir
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: tf-plugins-${{ runner.os }}-${{ hashFiles('infra/**/.terraform.lock.hcl') }}

      - name: Terraform environment configuration
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir = "~/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Terraform Init
        id: terraform_init
        run: terraform init -reconfigure -backend-config="prefix=terraform/test/${{ github.run_id }}-${ENVIRONMENT}"

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        run: terraform plan -lock-timeout=5m -input=false -var="environment=${ENVIRONMENT}" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -lock-timeout=5m -auto-approve tfplan

      - name: Tag commit on successful apply (PAT, debug)
        id: tag_commit
        if: success() && github.ref == 'refs/heads/main'
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAG_NAME: gcp-test-${{ steps.environment.outputs.environment }}
        run: |
          set -euo pipefail

          echo "Configuring git user:"
          git config user.name "tag-bot"
          git config user.email "tag-bot@users.noreply.github.com"
          git config user.name && git config user.email

          echo "Current HEAD:"
          git rev-parse HEAD
          echo "Workflows at HEAD:"
          git -C "$GITHUB_WORKSPACE" ls-tree -r HEAD -- .github/workflows || true

          echo "Setting PAT remote:"
          git remote set-url origin "https://x-access-token:${PAT}@github.com/${{ github.repository }}.git"
          echo "Push remote is:"
          git remote get-url --push origin

          echo "Creating annotated tag:"
          COMMIT_SHA="$(git rev-parse HEAD)"
          WF_LIST="$(git -C "$GITHUB_WORKSPACE" ls-tree -r HEAD --name-only .github/workflows || true)"
          {
            echo "env: $TAG_NAME"
            echo "commit: $COMMIT_SHA"
            echo "actor: $GITHUB_ACTOR"
            echo "run_id: $GITHUB_RUN_ID"
            echo "workflows:"
            echo "$WF_LIST"
          } > /tmp/tagmsg.txt

          git tag -fa "$TAG_NAME" -m "$(cat /tmp/tagmsg.txt)"

          echo "Show tag object locally:"
          git for-each-ref "refs/tags/$TAG_NAME" --format="%(objecttype) %(objectname) %(refname)"
          echo "--- tag message ---"
          git tag -n99 -l "$TAG_NAME"

          echo "Pushing tag via PAT:"
          git push -f origin "$TAG_NAME"

          echo "Verify tag on remote:"
          git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME" || { echo "Tag not found on remote"; exit 1; }

      - name: Upload tf artifacts
        if: always() && steps.terraform_init.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: tf-${{ steps.environment.outputs.environment }}
          path: |
            infra/tfplan
            infra/.terraform
          if-no-files-found: warn

      - name: Print Terraform state addresses
        if: always()
        run: terraform state list || true

      - name: Dump gcloud auth and project
        if: always()
        run: |
          gcloud auth list
          gcloud config get-value project

      - name: Terraform Destroy
        if: always() && steps.terraform_init.outcome == 'success'
        run: |
          set -euo pipefail

          terraform refresh -lock-timeout=5m -var="environment=${ENVIRONMENT}"
          terraform destroy -lock-timeout=5m -auto-approve -input=false -var="environment=${ENVIRONMENT}"
