name: Deploy to Netlify (prod)

on:
  push:
    branches: [main]
    paths:
      - 'public/**'
      - 'src/**'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4 # pick the node version your build needs
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run build:browser

      - run: npm install -g netlify-cli@17 # pin CLI version

      - name: Deploy to Netlify production
        run: |
          echo "🟢 Starting production deploy…"
          netlify deploy --prod --dir=public --message "GitHub ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
